{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.youndie",
    "module": "kompot-client",
    "version": "0.27.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.youndie",
          "module": "kompot-core",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-standard",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-analytics",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-realtime",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "form-core",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kompot-client-metadata-0.27.0.jar",
          "url": "kompot-client-0.27.0.46.jar",
          "size": 13731,
          "sha512": "bdbef9b15edaa0c6d83372bde2518d03b662f5ded052e6fec818fb869b42c8bc7c89a3566adc595c33e5168d0dea1e8135028cd5852278c6e5ce6ddd33291fc9",
          "sha256": "5d0b538b97734e71ffa92572bd64762806c14e2490c8b0a9e3b07f0e901ff10f",
          "sha1": "6fe4781375a015372ddc301ca9febe5cd96cc881",
          "md5": "7ed17c90b6d35c0e32ba4a935c59f318"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kompot-client-kotlin-0.27.0-sources.jar",
          "url": "kompot-client-0.27.0.46-sources.jar",
          "size": 24701,
          "sha512": "6559367a7a38ca805bfdba77a7cc78dca8b9def05a7ef1f7db785c45b64b1c9d76fc6a0af7ebf11057cddb09532ac83b12ba324f05afdb4beb881a08d37bf930",
          "sha256": "83b54c1e21b1a99bc93881ca8c76071c7807d0d6a117ba6c804f671ca3c01951",
          "sha1": "e31ed9695e11be41adf95003b724bf4ded745d18",
          "md5": "a76847a7070b6d7979ba62dffed18093"
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kompot-client-desktop/0.27.0.46/kompot-client-desktop-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-client-desktop",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kompot-client-desktop/0.27.0.46/kompot-client-desktop-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-client-desktop",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kompot-client-desktop/0.27.0.46/kompot-client-desktop-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-client-desktop",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kompot-client-wasm-js/0.27.0.46/kompot-client-wasm-js-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-client-wasm-js",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kompot-client-wasm-js/0.27.0.46/kompot-client-wasm-js-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-client-wasm-js",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kompot-client-wasm-js/0.27.0.46/kompot-client-wasm-js-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-client-wasm-js",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kompot-client-wasm-js/0.27.0.46/kompot-client-wasm-js-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-client-wasm-js",
        "version": "0.27.0.46"
      }
    }
  ]
}
