{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.youndie",
    "module": "kompot-ds-material-compose",
    "version": "0.27.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.youndie",
          "module": "kompot-client",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-ds-material",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-theme",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kompot-ds-material-compose-metadata-0.27.0.jar",
          "url": "kompot-ds-material-compose-0.27.0.46.jar",
          "size": 3140,
          "sha512": "6b8735a0db77138e13976f2b28734fe858f2a14905a31cdf79f29ac7acb587dccc07fe00703ce8ff824d5433a38bc3433198f47e4e72d0e52e9c46654454abf7",
          "sha256": "03481890f013050c8ce038d8ef5d090fe3b50c2f8034c12e42beaece5b5da377",
          "sha1": "03917831ffd1654dbea5baa6c34e4f55f75d5b92",
          "md5": "91995a1af7f4b07a1a111b0c9e854ba1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kompot-ds-material-compose-kotlin-0.27.0-sources.jar",
          "url": "kompot-ds-material-compose-0.27.0.46-sources.jar",
          "size": 3624,
          "sha512": "8ce19bbc8a581d3854647bf8be011f0f1672524ef5927306e1df9b1e10206a17b5fc4ea213433ccefce74c17f2c53c80f027ea00245eefaa8986c6076c724045",
          "sha256": "2a656f4aa8247ca43269b649be5dd47dee4f2c3ae6cbc1246d56bb8175e581c2",
          "sha1": "98b521302464e083419d8dc6bcc00e8925d5edcb",
          "md5": "82dccd637762b58a4f62edb24dbef163"
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kompot-ds-material-compose-desktop/0.27.0.46/kompot-ds-material-compose-desktop-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-ds-material-compose-desktop",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kompot-ds-material-compose-desktop/0.27.0.46/kompot-ds-material-compose-desktop-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-ds-material-compose-desktop",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kompot-ds-material-compose-desktop/0.27.0.46/kompot-ds-material-compose-desktop-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-ds-material-compose-desktop",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kompot-ds-material-compose-wasm-js/0.27.0.46/kompot-ds-material-compose-wasm-js-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-ds-material-compose-wasm-js",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kompot-ds-material-compose-wasm-js/0.27.0.46/kompot-ds-material-compose-wasm-js-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-ds-material-compose-wasm-js",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kompot-ds-material-compose-wasm-js/0.27.0.46/kompot-ds-material-compose-wasm-js-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-ds-material-compose-wasm-js",
        "version": "0.27.0.46"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kompot-ds-material-compose-wasm-js/0.27.0.46/kompot-ds-material-compose-wasm-js-0.27.0.46.module",
        "group": "io.github.youndie",
        "module": "kompot-ds-material-compose-wasm-js",
        "version": "0.27.0.46"
      }
    }
  ]
}
