{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kompot-client/0.27.0.46/kompot-client-0.27.0.46.module",
    "group": "io.github.youndie",
    "module": "kompot-client",
    "version": "0.27.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.youndie",
          "module": "kompot-core",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-standard",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-analytics",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-realtime",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "form-core",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kompot-client-desktop-0.27.0.jar",
          "url": "kompot-client-desktop-0.27.0.46.jar",
          "size": 167589,
          "sha512": "db2951836f8819f7a77e92136ab08f6b7341284e07bbe2eeb61aa83afba0df8b366d078d19507a0bb87ea423c6222402a7f8e7c8491b82558e233fc21071a432",
          "sha256": "187d6f6d890ea24a0641752f162f7ba4dc88ec4a6b2f5122b9ea1f265debb7a3",
          "sha1": "50a92dfbc6f30e7e979f50de7171f04d76e16620",
          "md5": "9c3c0291f23dd6a2e35c697f7fdfd0e9"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.youndie",
          "module": "kompot-core",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-standard",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-analytics",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-realtime",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "form-core",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-forms",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-images",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-wizard",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-commands",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "kompot-client-desktop-0.27.0.jar",
          "url": "kompot-client-desktop-0.27.0.46.jar",
          "size": 167589,
          "sha512": "db2951836f8819f7a77e92136ab08f6b7341284e07bbe2eeb61aa83afba0df8b366d078d19507a0bb87ea423c6222402a7f8e7c8491b82558e233fc21071a432",
          "sha256": "187d6f6d890ea24a0641752f162f7ba4dc88ec4a6b2f5122b9ea1f265debb7a3",
          "sha1": "50a92dfbc6f30e7e979f50de7171f04d76e16620",
          "md5": "9c3c0291f23dd6a2e35c697f7fdfd0e9"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kompot-client-desktop-0.27.0-sources.jar",
          "url": "kompot-client-desktop-0.27.0.46-sources.jar",
          "size": 26295,
          "sha512": "b3b9648605de36b4756a9d6d756572cd3c035735bc326bed034b10814704b387958eb486ee36498467744bb0a5e6b37a8092c088a1392ec6a09a4651cb7013e7",
          "sha256": "100f45172d9db9e4d2a948d683842509059a193b7f67179061a8f1a0868f89eb",
          "sha1": "60baa8a996bc98d6d84fef465532834117f85a74",
          "md5": "09d5f462ba0ebe82d720ff2709281b52"
        }
      ]
    }
  ]
}
