{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.11.0/kotlinx-coroutines-core-1.11.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.11.0.jar",
          "url": "kotlinx-coroutines-core-jvm-1.11.0.jar",
          "size": 1577052,
          "sha512": "6d7daee4c8d796dbf20f31225cd0a5d01c45d6f57fecd4e3b91c0e47fa59ac095f9605edad0fdd21954fb06eeab4a7b3a9c52cbe01f7033b058273642ec85e78",
          "sha256": "d1d75aa01dffbb4d1c520e67e4c4e7f5f6174718e7cb4632412503f2f0e604fa",
          "sha1": "3d57dc678bd8d72a60e7adf0eca5c54e3f4f4b79",
          "md5": "41a5e9a2f2c9affb9d9ab254be5a984f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.11.0.jar",
          "url": "kotlinx-coroutines-core-jvm-1.11.0.jar",
          "size": 1577052,
          "sha512": "6d7daee4c8d796dbf20f31225cd0a5d01c45d6f57fecd4e3b91c0e47fa59ac095f9605edad0fdd21954fb06eeab4a7b3a9c52cbe01f7033b058273642ec85e78",
          "sha256": "d1d75aa01dffbb4d1c520e67e4c4e7f5f6174718e7cb4632412503f2f0e604fa",
          "sha1": "3d57dc678bd8d72a60e7adf0eca5c54e3f4f4b79",
          "md5": "41a5e9a2f2c9affb9d9ab254be5a984f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.11.0-sources.jar",
          "url": "kotlinx-coroutines-core-jvm-1.11.0-sources.jar",
          "size": 438533,
          "sha512": "312bc1b0d8b5f92a63d6aa4184f100c0f1d04c34e2757b8fb9f31859d848fd6e31367d4a0ca91bafae351245e30ce5cf729ca2b6e7074be56dd7c7023a19c2a7",
          "sha256": "3e0847c0b463965404d5b6fe5d6868000a220b050180dec68501801e9439976a",
          "sha1": "9db4a9a41559fd6f57cfb0db791b3420c6389e1c",
          "md5": "69f3cd11cb3b88091d6958d0063f87a0"
        }
      ]
    }
  ]
}
