#!/usr/bin/env python3
"""kompot is pinned once, and this is what keeps it once.

It used to be pinned three times — the Gradle catalogue the server builds against, and two fields in
packages/kompot-web/package.json that the schema and corpus were fetched by. Renovate reads the
catalogue natively and each of the three resolved on its own, so a single bump produced a repository
pinned at 0.30.0.68, 0.30.0.67 and 0.30.0.68 at once. Nothing else would have noticed: schema:check
and corpus:check each compare a committed copy against *their own* pin and stay green while it drifts
away from the server's.

Now the scripts read the catalogue, so the drift is impossible rather than detected — and this guards
the thing that made it possible, which is a second pin appearing again.
"""
import json
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
problems = []

catalogue = (root / "gradle" / "libs.versions.toml").read_text(encoding="utf-8")
version = re.search(r'^kompot\s*=\s*"([^"]+)"', catalogue, re.MULTILINE)
if not version:
    sys.exit("gradle/libs.versions.toml declares no kompot version")

package = json.loads((root / "packages" / "kompot-web" / "package.json").read_text(encoding="utf-8"))
for field, value in (package.get("kompot") or {}).items():
    # A repository is a place; a version is the thing there must be only one of.
    if field != "repository" and re.search(r"\d+\.\d+", str(value)):
        problems.append(f"packages/kompot-web/package.json pins kompot again as kompot.{field} = {value}")

scripts = root / "packages" / "kompot-web" / "scripts"
# Both fetchers find their jar through kompotJar, and kompotJar finds the version in the catalogue.
jar = (scripts / "kompot-version.mjs").read_text(encoding="utf-8").partition("export function kompotJar(")[2]
if "kompotVersion(root)" not in jar:
    problems.append("kompot-version.mjs: kompotJar no longer takes the version from the catalogue")
for fetcher in ("fetch-corpus.mjs", "fetch-types.mjs"):
    if "kompotJar(" not in (scripts / fetcher).read_text(encoding="utf-8"):
        problems.append(f"{fetcher} no longer takes the version from the catalogue")

# The types are taken from the kompot-spec jar at the pinned version, so they cannot carry another one
# — unless the file was edited or regenerated by hand from something else. Its first line names the
# version it was taken from; checking it here costs no network, where `schema:check` needs the jar.
types = root / "packages" / "kompot-web" / "src" / "generated" / "kompot.ts"
first = types.read_text(encoding="utf-8").splitlines()[0]
printed = re.match(r"// kompot-spec (\S+),", first)
if not printed:
    problems.append(f"{types.relative_to(root)} does not say which kompot-spec it came from")
elif printed.group(1) != version.group(1):
    problems.append(f"{types.relative_to(root)} came from kompot-spec {printed.group(1)}")

if problems:
    print("kompot is pinned in more than one place:")
    for problem in problems:
        print(f"  {problem}")
    sys.exit(1)

print(f"kompot is {version.group(1)}, pinned once in gradle/libs.versions.toml and read from there")
