{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kompot-standard/0.27.0.46/kompot-standard-0.27.0.46.module",
    "group": "io.github.youndie",
    "module": "kompot-standard",
    "version": "0.27.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.youndie",
          "module": "kompot-core",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kompot-standard-jvm-0.27.0.jar",
          "url": "kompot-standard-jvm-0.27.0.46.jar",
          "size": 106614,
          "sha512": "e05c1d88233df1400466a8c9442f2fdbb95ebc9b4386268d5fedf2046b908baa918d0f2f2f71bfd10ce1e654c17311af94240a9857aee7d2bfdc9cbde801b7c8",
          "sha256": "9c6b6a6763015da367b37ebc40ba17ae8ebac814c47bcab762fbbc8b132aa50c",
          "sha1": "4c77758a6ace7d189bab2ed7d3740674d2ed29e5",
          "md5": "f4a44f6306cf7313e3581489bcdda844"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.youndie",
          "module": "kompot-core",
          "version": {
            "requires": "0.27.0.46"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "io.github.youndie",
          "module": "kompot-registry-annotations",
          "version": {
            "requires": "0.27.0.46"
          }
        }
      ],
      "files": [
        {
          "name": "kompot-standard-jvm-0.27.0.jar",
          "url": "kompot-standard-jvm-0.27.0.46.jar",
          "size": 106614,
          "sha512": "e05c1d88233df1400466a8c9442f2fdbb95ebc9b4386268d5fedf2046b908baa918d0f2f2f71bfd10ce1e654c17311af94240a9857aee7d2bfdc9cbde801b7c8",
          "sha256": "9c6b6a6763015da367b37ebc40ba17ae8ebac814c47bcab762fbbc8b132aa50c",
          "sha1": "4c77758a6ace7d189bab2ed7d3740674d2ed29e5",
          "md5": "f4a44f6306cf7313e3581489bcdda844"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kompot-standard-jvm-0.27.0-sources.jar",
          "url": "kompot-standard-jvm-0.27.0.46-sources.jar",
          "size": 7461,
          "sha512": "b95294b93866c47f049539d5ff0895040361ba07e348580216fbd57e36d038bcc1fa2a66415d525c08d181f46c6067f76c0c31f469ace0686d11dc21b10d4943",
          "sha256": "4538eb424d66b11d39f9c504d987ca849409c55182cbd0a8d03413d350b1d27a",
          "sha1": "e8d7bba1dfa7a50319302dda373fc141e06011c4",
          "md5": "2fd94d9f2c1769573249559e9ed24938"
        }
      ]
    }
  ]
}
