{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kompot-core/0.27.0.46/kompot-core-0.27.0.46.module",
    "group": "io.github.youndie",
    "module": "kompot-core",
    "version": "0.27.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kompot-core-iosSimulatorArm64Main-0.27.0.klib",
          "url": "kompot-core-iossimulatorarm64-0.27.0.46.klib",
          "size": 46011,
          "sha512": "dba300f50167ec22736cf9420878c6382a9a03744d74b386333bda1fdda9c98eee44736ad084da866857d20bafc7aab9904d85b810f2ab921dce4e4c50826de8",
          "sha256": "f3f7c562bbffa338a32b559540ccb8e3aaa057f0199621e2765b64f141d355df",
          "sha1": "d5e82e6471721cabef569d809924288f1ddf0bb5",
          "md5": "d9e626f4a3ad75991efbfb3a4e7cbe3a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kompot-core-iossimulatorarm64-0.27.0-sources.jar",
          "url": "kompot-core-iossimulatorarm64-0.27.0.46-sources.jar",
          "size": 7179,
          "sha512": "593b463f24417473c85297ec925ec3c4667c08e243b132e702c8682f7b687cd84cdf705b97638565866bd4f3f00950df0b57ca732f8fe30a7d62ab8887ae8710",
          "sha256": "fb3846f0f684caf5751a091f41d4bae6d2f1712290dae6a97a465aa94946b222",
          "sha1": "c98dcb8c83248b1efe254920ce59d27f56a1ac24",
          "md5": "75f366b0fc66fb9c85bc0b4c55ff23c8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kompot-core-iossimulatorarm64-0.27.0-metadata.jar",
          "url": "kompot-core-iossimulatorarm64-0.27.0.46-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
